### ISSUE TITLE
MIDX dataset with no name causes crash

### ISSUE THREAD

**Issue by spetruzza** [sci-visus/OpenVisus#13]
The following without a "name" parameter for the dataset make the viewer crash.
```
<dataset typename='IdxMultipleDataset'>
  <dataset url='http://atlantis.sci.utah.edu/mod_visus?dataset=2kbit1'>
		<M value="1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1 0.0 0.0 0.0 0.0 1.0"/>
  </dataset>
</dataset>
```

We could generate a random name or simply report the error to the user.

**Comment by scrgiorgio** [comment]
please provide call stack and try to debug

**Comment by scrgiorgio** [comment]
fixed see file IdxMultipleDataset line 963:

String default_name = StringUtils::format() << "child_" << std::setw(4) << std::setfill('0') << cstring((int)this->childs.size());
..
child.name = StringUtils::trim(istream.readInline("name", istream.readInline("id")));
...
  if (child.name.empty() || this->childs.find(child.name) != this->childs.end())
    child.name = default_name;
