### ISSUE TITLE
fatal error: 'Foundation/NSAutoreleasePool.h' file not found

### ISSUE THREAD

**Issue by yurivict** [sci-visus/OpenVisus#213]
Error:
```
/disk-samsung/freebsd-ports/science/openvisus/work/OpenVisus-2.2.65/Libs/Kernel/src/Kernel.mm:41:9: fatal error: 'Foundation/NSAutoreleasePool.h' file not found
#import <Foundation/NSAutoreleasePool.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

[This](https://github.com/sci-visus/OpenVisus/blob/master/Libs/Kernel/src/Kernel.mm#L41) code is obviously wrong because clang certainly doesn't install the file ```Foundation/NSAutoreleasePool.h```.

Version: 2.2.65
FreeBSD 13.1 STABLE

**Comment by scrgiorgio** [comment]
OpenVisus is assuming:

- Windows: Microsoft Visual Studio
- Apple: XCode
- Others: GNUC

I pushed a commit but not sure if it fixes the problem:
https://github.com/sci-visus/OpenVisus/commit/158f7356fbe56c640f785b64e8a8008195297bb5

**Comment by yurivict** [comment]
It is sufficient to build this module on FreeBSD.
