### ISSUE TITLE
Unable to import OpenVisus in python 3.7

### ISSUE THREAD

**Issue by n8vm** [sci-visus/OpenVisus#24]
When I try to import OpenVisus, __init__.py calls "from .OpenVisus import *", which returns the error message: " ModuleNotFoundError: No module named 'OpenVisus.OpenVisus'.

By changing "from .OpenVisus import *" to "from . import *", the error goes away.

**Comment by pascucci** [comment]
Is there a “.” In the name?
After the second option do you get all the ViSUS functions?
V

**Comment by n8vm** [comment]
The second option seems to give me all the ViSUS functions. I think I can make a pull request with a quick fix for this and for the other issue I just opened.

**Comment by scrgiorgio** [comment]
Merged pull request: https://github.com/sci-visus/OpenVisus/pull/26
