### ISSUE TITLE
Scripting defaults needs an update

### ISSUE THREAD

**Issue by anikethvenkat** [sci-visus/OpenVisus#34]
Scripting defaults (like 2d/Blur) are broken after the new from and toNumPy api's.

Possible Fix: 
import numpy as np
kernel=np.array([[1/9.0,1/9.0,1/9.0], [1/9.0,1/9.0,1/9.0] , [1/9.0,1/9.0,1/9.0]])
output=ArrayUtils.convolve(input,Array.fromNumPy(kernel),aborted)

![image](https://user-images.githubusercontent.com/13954719/51728757-8a286b80-202e-11e9-899a-2051324c720f.png)

**Comment by scrgiorgio** [comment]
fixed
