### ISSUE TITLE
Midx blending issue at the boundaries

### ISSUE THREAD

**Issue by anikethvenkat** [sci-visus/OpenVisus#37]
See video.

Viewing individual fields as an average of itself has no issues at the boundary. But when you average two fields there seems to be a visual artefact.

[midx_blending_visual_bug.zip](https://github.com/sci-visus/OpenVisus/files/2794893/midx_blending_visual_bug.zip)

**Comment by scrgiorgio** [comment]
aniketh,
after what we said, do you know possible workaround?
