### ISSUE TITLE
Palette doesn't update statistics (unless you trigger a new query)

### ISSUE THREAD

**Issue by anikethvenkat** [sci-visus/OpenVisus#39]
Issue: Open dataset, open palette.
Observation: Input stats are empty. The stats appear when you trigger a new query (by manipulator or by refreshing the data).

See video...
[palette_issue.zip](https://github.com/sci-visus/OpenVisus/files/2795029/palette_issue.zip)

**Comment by spetruzza** [comment]
I think that was a wanted (lazy) behavior, but at the same time it should not be a big deal just to update the statistics “on palette window open”.
