### ISSUE TITLE
Python documentation on wiki broken/unavailable

### ISSUE THREAD

**Issue by n8vm** [sci-visus/OpenVisus#48]
I noticed there was a link on wiki.visus.org on the Python bindings for visus, but it seems to either be broken or not written.

https://wiki.visus.org/index.php/ViSUS_Python

It would be really helpful for those of us using Visus in our python applications to have a more official documentation source than just the occasional jupyter notebook example.

**Comment by spetruzza** [comment]
Fixed. There was a page for it, but when I changed the name in the navbar it broke the link.

That should definitely be extended with more use examples

**Comment by n8vm** [comment]
Thanks!
