### ISSUE TITLE
some docker images no longer building

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisus#64]
Docker build broken for opensuse and anaconda (see Docker/build_all.sh).

**Comment by cchriste** [comment]
For Dockerfile.anaconda, since that build is deployed in Anaconda Cloud, this is probably a new issue with the Dockerfile. 

Similarly, since travis-ci opensuse build succeeds, Dockerfile.opensuse may need updating.

**Comment by scrgiorgio** [comment]
Thanks!
please give a look now.
And you are right, I'm not building mod_visus for conda... do we really want it?

**Comment by cchriste** [comment]
The ondemand module is built on anaconda, and the reason it fails is the lack of mod_visus.
So yes, please: keep mod_visus in anaconda. Can you please re-enable it? I'll pay attention to how you do it so I can fix it myself next time.

**Comment by scrgiorgio** [comment]
I unlocked the mod_visus compilation under Visus (branch scrgiorgio):

https://github.com/sci-visus/OpenVisus/commit/9a7355fde9c31b2b873e606aafe47d63d2f90d30


but it does not find apache (even if it's installed automatically)...
Cameron can you give a look what's going on?

**Comment by cchriste** [comment]
I'd say the best place to do this is through Travis, since otherwise it "trashes" your system.

I don't know how to fix this, but just trying it briefly shows the error that **sudo priviledges are necessary to install apache2 and apache2-dev**, which is done in build.sh just before the conda-specific install is started: 
```
if (( OSX != 1 && VISUS_MODVISUS == 1 )); then
  InstallApache
fi
```

The biggest reason for users to install the non-gui version of OpenVisus would be to enable access to their data using mod_visus. All the Docker builds do this, and this issue would have immediately shown up if they had been added to Travis as requested (https://github.com/sci-visus/OpenVisus/issues/52).

**Comment by scrgiorgio** [comment]
Actually to build using docker command as suggested in Travis.
Even if apache and apache-devel get installed just fine, cmake fails to
find it... do you have any idea why? It happens only in conda env.

**Comment by cchriste** [comment]
I do not know why. Why did it work before, as recently as 1.3.38? What changed?
