### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [sci-visus/OpenVisus#8]
https://github.com/sci-visus/OpenVisus/blob/7b389af2eba273c4440a32b82402a35e55e14f75/CMakeLists.txt#L66

Please provide an AppImage for Linux, you should be able to almost literally copy 1:1 the example from https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci.

Thanks!

**Comment by scrgiorgio** [comment]
I think we are already copying the necessary libraries and we don't need linuxdeployqt right now . In any case if we had problems about linux distribution in the future, we will use that tool. Thanks for pointing that out.
