### ISSUE TITLE
Add compression parameters (useful for e.g., compressing NEON data sets)

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/OpenVisus#82]
Some compression schemes could benefit from parameter tuning. For example, the NEON data set when compressed with JPG by default produces quite a bit of artifacts, but with a different set of parameters the artifacts are gone, while retaining reasonable compression ratio. I propose adding a list of floating point values after the compression scheme, e.g. instead of (jpg) we have (jpg-1.0, 2.4, 3).

The compression scheme can still be parsed by extracting the substring before the dash "-". The list of values can be parsed and stored as std::vector<double>, and forwarded to the appropriate Encoder, which will be able to make sense of the list. Future parameters can just be appended to the list and backward-compatibility is maintained as long as we do not change the meaning of the existing parameters.

**Comment by scrgiorgio** [comment]
OK fine with that. Just wondering if the compression scheme should be a C++ std::vector<String> or it's enough to pass the String to the encoder which will do internally the parsing.

**Comment by hoangthaiduong** [comment]
I think it should be parsed and stored as std::vector before passing to the encoder. This should avoid having to implement string parsing in every encoder class.

**Comment by scrgiorgio** [comment]
Hi Duong,
what do you think?

https://github.com/sci-visus/OpenVisus/commit/2e5afca8f3e1c836ff89e6c63ef00353c0ff172e

**Comment by hoangthaiduong** [comment]
Thank you, Giorgio. I think this is almost there. 2 points:

- The vector of options I think should be passed to the constructors of the encoder instead of to the encode/decode functions. After all, we are using the same parameters for all blocks. Would it be better to pass it once and reuse later on?

- If you think it's better to pass the options to the encode/decode functions instead, then can we make this a vector<double> instead of vector<String>? This would avoid having to parse from String to numbers, or do String comparison repeatedly for every block. We can just put comments in the code to make it clear which number corresponds to which option.

**Comment by scrgiorgio** [comment]
Hi Duon,

actually the encoders are built on the DLL init section, so they are
Singleton.
WHat you are proposing instead is build the Encoder/Decoder on the fly.....
are you sure this is what you are looking for?

**Comment by hoangthaiduong** [comment]
I see. Then a better solution could be we add another member function to the Encoder/Decoder to set the options. Something like Encoder->SetOptions(vector of Strings). Inside each encoder, we will know exactly how to parse the vector of options and store them to use in every invocation of encode() or decode() later on. How about that?

**Comment by scrgiorgio** [comment]
let me think because since it's a singleton it's a shared instance and
cannot be modified.
But I see your point, let me think if it's something I need to change anyway

**Comment by scrgiorgio** [comment]
What do you think of this one:

https://github.com/sci-visus/OpenVisus/commit/e331d2e3e886b1752718a17b5180a9187769371a

there are examples about options inside ZipEncoder and FreeImageEncoder

**Comment by hoangthaiduong** [comment]
Thanks Giorgio. I created a PR at https://github.com/sci-visus/OpenVisus/pulls
