### ISSUE TITLE
visus compress-dataset seems to not work

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/OpenVisus#86]
The compress-dataset command seems broken. When tried on a dataset, the data is either not compressed, or is different from data compressed using the "import export" commands. As a work around, I'm attaching a Python script that will do the compression using "import export" commands.

[idx-compress.zip](https://github.com/sci-visus/OpenVisus/files/3683494/idx-compress.zip)

**Comment by scrgiorgio** [comment]
Hi Duong, can you share exactly what is not working? I need the command
line in order to debug. Usually it's better if you can replicate the issue
with a toy example (like cat in dataset directory).

**Comment by scrgiorgio** [comment]
I think I fixed it.

https://github.com/sci-visus/OpenVisus/commit/fc067c35ba514f9851a135eee4666869bad419f3

**Comment by hoangthaiduong** [comment]
Sorry Giorgio I didn't get a chance to produce a reproducible test yet. Will get around doing that today. I see that you changed

    String compression = query->field.default_compression;
to
    String compression = block_header.getCompression();

The problem with the second line is that, if the compression has parameters, during decompression I don't get the parameters passed to the Decoder, only the name of the compression itself (e.g. zip, zfp etc). I need to get zfp-16 not just zfp to be able to decode correctly. What is the problem with the first approach?

**Comment by scrgiorgio** [comment]
ok that was the offending line for compressDataset.

We first write the data uncompressed: each block actually store (in the
header) the information that the block is stored as not compressed.

When later i'm trying to compress it (i.e. compressDataset), first i read
the block, and I realize from the header it's still uncompressed; then I
compress it using the new compression scheme.

It could even be that different blocks are compressed with different
compression algorithms (depending on their numbers, read coarse vs fine
blocks), so we should really stick to use the header as a source of
information if the block was compressed or not. We should not overrule this
using IDX...

Does that make sense?

**Comment by hoangthaiduong** [comment]
Hi Giorgio. So for now I think we can leave things the way they have been (compression info read from block header instead of from .idx). For zfp I can decompress without this information, so it's fine. In the future though, maybe we have to think more on how to store compression parameters. I made a change here to make this work with zfp, please consider merging it https://github.com/sci-visus/OpenVisus/pull/88
