### ISSUE TITLE
Viewer crashes on palette change

### ISSUE THREAD

**Issue by spetruzza** [sci-visus/OpenVisus#92]
The viewer crashes on palette change when selecting any colormap after "lut16".
Happens on latest "scrgiorgio" with any dataset

**Comment by scrgiorgio** [comment]
Arw you sure it's still happening in my branch?

Il mar 17 dic 2019, 19:31 spetruzza <notifications@github.com> ha scritto:

**Comment by spetruzza** [comment]
it happened after making pull, make clean, make install. I will try next to delete everything and build from scratch

**Comment by spetruzza** [comment]
confirm, the latest "scrgiorgio" visusviewer built from scratch crashes on palette change (even with the default cat dataset). On Mac 10.15.2, but I remember seeing the same issue on 10.14

**Comment by scrgiorgio** [comment]
Hi Steve,

I tried on my 2 windows machine but I cannot replicate it.
Can you run inside xcode and send me the call stack?
Thanks,Giorgio.
