### ISSUE TITLE
Curl does not build on Linux

### ISSUE THREAD

**Issue by ptbremer** [sci-visus/OpenVisus#93]
On the LLNL clusters the OpenVisus master branch does not build because the system misses stropts.h

external/curl/lib/if2ip.c:47:23: fatal error: stropts.h: No such file or directory

removing it from the source temporarily fixes the issue. The correct solution seems to be to make sure we use 

HAVE_STROPTS_H=0

not sure how to do that since we are building from pre-configured source and this might not apply to all systems

**Comment by scrgiorgio** [comment]
yes we decided to use pre-configured curl because it was causing too many
problems.
I think setting HAVE_STROPTS_H=0 default on linux it's just fine.
What do you think?
