### ISSUE TITLE
Build fails when not building with VISUS_PYTHON enabled

### ISSUE THREAD

**Issue by Twinklebear** [sci-visus/OpenVisus#95]
When `VISUS_PYTHON` is off this line is compiled https://github.com/sci-visus/OpenVisus/blob/master/Libs/Db/src/IdxMultipleDataset.cpp#L1034 and the `FormatString` function is missing

**Comment by scrgiorgio** [comment]
thanks will for pointing it out.

**Comment by Twinklebear** [comment]
fixed in 18546bf71672a088d52c664a6f6c42f5e74fba9c
